apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Program Files (x86)\kompose\kompose.exe convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: dhbw-seminarbeit-displaydata
  name: dhbw-seminarbeit-displaydata
spec:
  ports:
  - name: "4001"
    port: 4001
    targetPort: 4001
  selector:
    io.kompose.service: dhbw-seminarbeit-displaydata
status:
  loadBalancer: {}
