apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: dhbw-seminarbeit-displaydata-ingress
spec:
  rules:
  - host: display.co2ampel.example.internal
    http:
      paths:
      - path: /data
        pathType: Exact
        backend:
          serviceName: dhbw-seminarbeit-displaydata 
          servicePort: 4001